-- create table for users
CREATE TABLE USER(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    USERNAME VARCHAR(255)
);
ALTER TABLE USER ADD CONSTRAINT USER_PKEY PRIMARY KEY(ID);

-- create table for notes
CREATE TABLE NOTE(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CONTENT VARCHAR(1024),
    LOCAL_DATE_TIME TIMESTAMP,
    AUTHOR_ID BIGINT
);
ALTER TABLE NOTE ADD CONSTRAINT NOTE_PKEY PRIMARY KEY(ID);
ALTER TABLE NOTE ADD CONSTRAINT NOTE_AUTH_FKEY FOREIGN KEY(AUTHOR_ID) REFERENCES USER(ID) NOCHECK;